In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
test = pd.read_csv('data/RentListingInquries_FE_test.csv')
train = pd.read_csv('data/RentListingInquries_FE_train.csv')
train.head()

,bathrooms,bedrooms,price,price_bathrooms,price_bedrooms,room_diff,room_num,Year,Month,Day,...,walk,walls,war,washer,water,wheelchair,wifi,windows,work,interest_level
0,1.5,3,3000,1200.0,750.000000,-1.5,4.5,2016,6,24,...,0,0,0,0,0,0,0,0,0,1
1,1.0,2,5465,2732.5,1821.666667,-1.0,3.0,2016,6,12,...,0,0,0,0,0,0,0,0,0,2
2,1.0,1,2850,1425.0,1425.000000,0.0,2.0,2016,4,17,...,0,0,0,0,0,0,0,0,0,0
3,1.0,1,3275,1637.5,1637.500000,0.0,2.0,2016,4,18,...,0,0,0,0,0,0,0,0,0,2
4,1.0,4,3350,1675.0,670.000000,-3.0,5.0,2016,4,28,...,0,0,1,0,0,0,0,0,0,2

In [3]:
y_train = train['interest_level']
x_train = train.drop('interest_level',axis=1)

数据已经经过特征工程处理，所以接下来只需要掉包......(开心)

# 缺省参数的决策树

In [4]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import roc_auc_score
from sklearn.metrics import log_loss
dtree = DecisionTreeClassifier()
dtree.fit(x_train,y_train)
y_pred = dtree.predict_proba(x_train)
print('训练集上的正确率为：',dtree.score(x_train,y_train))
print('训练集上的log_loss为：',log_loss(y_train,y_pred))

训练集上的正确率为： 0.9994123845031609
训练集上的log_loss为： 0.0008252104193618377

In [18]:
dtree.get_params

<bound method BaseEstimator.get_params of DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')>

In [5]:
df = pd.DataFrame({'columns':x_train.columns,'importance':dtree.feature_importances_.T})
df.sort_values(by=['importance'],ascending=False)

                    columns  importance
4            price_bedrooms    0.111366
23                 distance    0.083996
3           price_bathrooms    0.068322
12                     hour    0.064494
2                     price    0.063961
9                       Day    0.062962
11                     Yday    0.060102
24   display_address_pred_0    0.050542
26   display_address_pred_2    0.050356
25   display_address_pred_1    0.047905
10                     Wday    0.039327
22                  cenroid    0.031109
96                      fee    0.021758
128                 laundry    0.010406
15            top_5_manager    0.008755
83               dishwasher    0.007980
35                  allowed    0.007814
113                hardwood    0.007564
17            top_1_manager    0.007561
57                 building    0.007012
91                 elevator    0.006803
13           top_10_manager    0.006668
8                     Month    0.006300
85                  doorman    0.006147
106               furnished    0.005818
19           top_15_manager    0.005730
211                    unit    0.005649
184                 simplex    0.005630
84                     dogs    0.005108
163                  prewar    0.005024
..                      ...         ...
51                billiards    0.000000
161                    post    0.000000
159                playroom    0.000000
90                     elev    0.000000
80               decorative    0.000000
156                     pet    0.000000
81                  details    0.000000
47                  bedford    0.000000
144                  modern    0.000000
86                      dry    0.000000
111                     gut    0.000000
170                    rent    0.000000
187                skylight    0.000000
171               residents    0.000000
40                 attended    0.000000
67                childrens    0.000000
28                       24    0.000000
68                    clean    0.000000
182                  shares    0.000000
181                  shared    0.000000
180                   share    0.000000
179                services    0.000000
178                 service    0.000000
177                   sauna    0.000000
95               facilities    0.000000
175                 rooftop    0.000000
132                  living    0.000000
69                 cleaning    0.000000
172                    rise    0.000000
72                  closets    0.000000

[227 rows x 2 columns]

按照重要性对特征进行排序，取大于0的特征看看

In [6]:
df = df[df.importance>0]
df

                    columns  importance
0                 bathrooms    0.002821
1                  bedrooms    0.003125
2                     price    0.063961
3           price_bathrooms    0.068322
4            price_bedrooms    0.111366
5                 room_diff    0.002910
6                  room_num    0.004320
8                     Month    0.006300
9                       Day    0.062962
10                     Wday    0.039327
11                     Yday    0.060102
12                     hour    0.064494
13           top_10_manager    0.006668
14           top_25_manager    0.004272
15            top_5_manager    0.008755
16           top_50_manager    0.002526
17            top_1_manager    0.007561
18            top_2_manager    0.004820
19           top_15_manager    0.005730
20           top_20_manager    0.004194
21           top_30_manager    0.003209
22                  cenroid    0.031109
23                 distance    0.083996
24   display_address_pred_0    0.050542
25   display_address_pred_1    0.047905
26   display_address_pred_2    0.050356
29                      2br    0.000056
30                      3br    0.000089
31                       ac    0.000074
32                   access    0.002089
..                      ...         ...
176                    room    0.003098
183                   short    0.000231
184                 simplex    0.005630
185                    site    0.000273
186                   sized    0.000059
188                   space    0.004173
189                spacious    0.000226
190                   speed    0.001420
193               stainless    0.000057
196                 storage    0.000285
198                  sublet    0.000079
200                   super    0.000124
201          superintendent    0.000075
202                swimming    0.001997
203                  tenant    0.000073
205                 terrace    0.002650
206                    time    0.000111
211                    unit    0.005649
212               utilities    0.000073
213                   valet    0.000059
215                    view    0.000059
217                 virtual    0.000131
218                    walk    0.000145
220                     war    0.003575
221                  washer    0.000429
222                   water    0.000129
223              wheelchair    0.001562
224                    wifi    0.000057
225                 windows    0.000134
226                    work    0.000071

[152 rows x 2 columns]

想要选取一些重要的特征再进行建模的话，可能要把特征数目调少一些

In [7]:
df = df[df.importance>0.005]
df

                    columns  importance
2                     price    0.063961
3           price_bathrooms    0.068322
4            price_bedrooms    0.111366
8                     Month    0.006300
9                       Day    0.062962
10                     Wday    0.039327
11                     Yday    0.060102
12                     hour    0.064494
13           top_10_manager    0.006668
15            top_5_manager    0.008755
17            top_1_manager    0.007561
19           top_15_manager    0.005730
22                  cenroid    0.031109
23                 distance    0.083996
24   display_address_pred_0    0.050542
25   display_address_pred_1    0.047905
26   display_address_pred_2    0.050356
35                  allowed    0.007814
57                 building    0.007012
83               dishwasher    0.007980
84                     dogs    0.005108
85                  doorman    0.006147
91                 elevator    0.006803
96                      fee    0.021758
106               furnished    0.005818
113                hardwood    0.007564
128                 laundry    0.010406
163                  prewar    0.005024
184                 simplex    0.005630
211                    unit    0.005649

In [8]:
from numpy import sort
from sklearn.feature_selection import SelectFromModel
from sklearn.metrics import accuracy_score
# Fit model using each importance as a threshold
thresholds = sort(df.importance)
for thresh in thresholds:
  # select features using threshold
  selection = SelectFromModel(dtree, threshold=thresh, prefit=True)
  select_x_train = selection.transform(x_train)

  # train model
  selection_model = DecisionTreeClassifier()
  selection_model.fit(select_x_train, y_train)
    
# eval model
  select_x_train = selection.transform(x_train)
  y_pred = selection_model.predict(select_x_train)
  predictions = [round(value) for value in y_pred]
  accuracy = accuracy_score(y_train, predictions)
  print("Thresh=%.3f, n=%d, Accuracy: %.2f%%" % (thresh, select_x_train.shape[1],
      accuracy*100.0))

Thresh=0.005, n=30, Accuracy: 99.93%
Thresh=0.005, n=29, Accuracy: 99.93%
Thresh=0.006, n=28, Accuracy: 99.93%
Thresh=0.006, n=27, Accuracy: 99.93%
Thresh=0.006, n=26, Accuracy: 99.93%
Thresh=0.006, n=25, Accuracy: 99.93%
Thresh=0.006, n=24, Accuracy: 99.93%
Thresh=0.006, n=23, Accuracy: 99.93%
Thresh=0.007, n=22, Accuracy: 99.93%
Thresh=0.007, n=21, Accuracy: 99.93%
Thresh=0.007, n=20, Accuracy: 99.93%
Thresh=0.008, n=19, Accuracy: 99.93%
Thresh=0.008, n=18, Accuracy: 99.93%
Thresh=0.008, n=17, Accuracy: 99.92%
Thresh=0.008, n=16, Accuracy: 99.92%
Thresh=0.009, n=15, Accuracy: 99.91%
Thresh=0.010, n=14, Accuracy: 99.89%
Thresh=0.022, n=13, Accuracy: 99.88%
Thresh=0.031, n=12, Accuracy: 99.87%
Thresh=0.039, n=11, Accuracy: 99.87%
Thresh=0.048, n=10, Accuracy: 99.87%
Thresh=0.050, n=9, Accuracy: 99.87%
Thresh=0.051, n=8, Accuracy: 99.87%
Thresh=0.060, n=7, Accuracy: 99.65%
Thresh=0.063, n=6, Accuracy: 99.57%
Thresh=0.064, n=5, Accuracy: 96.18%
Thresh=0.064, n=4, Accuracy: 96.16%
Thresh=0.068, n=3, Accuracy: 90.45%
Thresh=0.084, n=2, Accuracy: 89.70%
Thresh=0.111, n=1, Accuracy: 71.57%

经过特征选择，发现当thresh为0.07时的结果都还是挺好的

# 决策树参数调优

In [15]:
from sklearn.model_selection import GridSearchCV
max_depth = range(1,20)
min_samples_leaf = range(1,30)
dtree2 = DecisionTreeClassifier()
param_grid = {'max_depth':max_depth,'min_samples_leaf':min_samples_leaf}
grid = GridSearchCV(dtree2,param_grid=param_grid,cv=5,scoring='accuracy')
grid.fit(x_train,y_train)

GridSearchCV(cv=5, error_score='raise',
       estimator=DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best'),
       fit_params=None, iid=True, n_jobs=1,
       param_grid={'max_depth': range(1, 20), 'min_samples_leaf': range(1, 30)},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring='accuracy', verbose=0)

In [16]:
print(grid.best_score_)
print(grid.best_params_)

0.7129599610958016
{'max_depth': 9, 'min_samples_leaf': 21}

结果比缺省参数的还要差，原因可能是树的深度问题，因为时间成本太高，就不再试了